## Lectura base

### Librerías

In [7]:
import pandas as pd
import numpy as np

### Carga archivo

In [8]:
df = pd.read_excel(r"C:\Users\DavidSebastianSantos\Downloads\data_cargo.xlsx")
df

,fuente,id,job_title,descripcion_job,cargo_reducido,cargo_ampliado,Unnamed: 6
0,CT,121353B1447F3DBF61373E686DCF3405,asesor comercial call center portugues fluido,hablas portugues con fluidez te apasionan las ...,Asesor comercial call center,Asesor comercial bilingüe portugués,False
1,CT,DCAD67497EF99F0561373E686DCF3405,soldador con experiencia,tener bases claras al operar las diferentes he...,Soldador,Soldador especializado en soldadura TIG,False
2,CT,921FE1BAFAD2ED7C61373E686DCF3405,auxiliar logistico con manejo de estibador ele...,"importante empresa del sector de alimentos, re...",Auxiliar de bodega,Auxiliar logístico con manejo de estibador elé...,False
3,CT,2A0F5B5C9D71F0D761373E686DCF3405,motorista,empresa del sector de distribucion de alimento...,Conductor,Motorista,False
4,CT,75E581D691581B9461373E686DCF3405,psicologoa con experiencia,se necesita psicologoa con posgrado en temas r...,Psicólogo,Psicólogo especialista en salud mental,False
...,...,...,...,...,...,...,...
295,CT,ED3D1FB42510128B61373E686DCF3405,"conductor de ambulancia, guasca manejo de vehi...",importante empresa del sector salud esta en bu...,Conductor de ambulancia,Conductor de ambulancia,True
296,CT,A8247246D4C1788461373E686DCF3405,aprendiz tecnico o tecnologo administrativo,g4s es la multinacional lider en soluciones de...,Aprendiz técnico o tecnólogo administrativo,Aprendiz técnico o tecnólogo administrativo,True
297,CT,CC0A5E9E2300910561373E686DCF3405,auxiliar administrativo ventas,multinacional en el sector financiero dedicada...,Auxiliar administrativo de ventas,Auxiliar administrativo de ventas,True
298,CT,274D3A61F9B2EF4561373E686DCF3405,analista de importaciones,objetivo del cargogestionar de manera integral...,Analista de Importaciones,Analista de importaciones,True
299,CT,9CFB9B17A6076D9C61373E686DCF3405,auxiliar cuarto frio auxiliar logistico zipaquira,empresa lider del sector alimenticio ubicada e...,Auxiliar de cuarto frío,Auxiliar de cuarto frío,True

### Consultas

In [9]:
fuentes = df[['fuente']].drop_duplicates()
fuentes

  fuente
0     CT

In [10]:
df["fuente"].count()

300